import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "./page";
import AuthGuard from "@/src/components/auth/authGuard";
import { Toaster } from "sonner";
import ClientProvider from "@/src/store/clientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <ClientProvider>
          <Toaster />
          <AuthGuard>
            <Layout children={children} />
          </AuthGuard>
        </ClientProvider>
      </body>
    </html>
  );
}
