export const storeRows = [
    {
        id: "ST035",
        store: "San Francisco Bay Trends",
        city: "San Francisco",
        state: "CA",
    },
    { id: "ST046", store: "Phoenix Sunwear", city: "Phoenix", state: "AZ" },
    { id: "ST064", store: "Dallas Ranch Supply", city: "Dallas", state: "TX" },
    { id: "ST066", store: "Atlanta Outfitters", city: "Atlanta", state: "GA" },
    {
        id: "ST073",
        store: "Nashville Melody Music Store",
        city: "Nashville",
        state: "TN",
    },
    { id: "ST074", store: "New York Empire Eats", city: "New York", state: "NY" },
    { id: "ST091", store: "Denver Peaks Outdoor", city: "Denver", state: "CO" },
    {
        id: "ST094",
        store: "Philadelphia Liberty Market",
        city: "Philadelphia",
        state: "PA",
    },
    { id: "ST097", store: "Boston Harbor Books", city: "Boston", state: "MA" },
    { id: "ST101", store: "Austin Vibe Co.", city: "Austin", state: "TX" },
    { id: "ST131", store: "Los Angeles Luxe", city: "Los Angeles", state: "CA" },
    {
        id: "ST150",
        store: "Houston Harvest Market",
        city: "Houston",
        state: "TX",
    },
    {
        id: "ST151",
        store: "Portland Evergreen Goods",
        city: "Portland",
        state: "OR",
    },
    {
        id: "ST156",
        store: "Chicago Charm Boutique",
        city: "Chicago",
        state: "IL",
    },
    {
        id: "ST163",
        store: "Las Vegas Neon Treasures",
        city: "Las Vegas",
        state: "NV",
    },
    { id: "ST175", store: "Seattle Skyline Goods", city: "Seattle", state: "WA" },
    { id: "ST176", store: "Miami Breeze Apparel", city: "Miami", state: "FL" },
    {
        id: "ST177",
        store: "San Diego Wave Surf Shop",
        city: "San Diego",
        state: "CA",
    },
    {
        id: "ST193",
        store: "Charlotte Queen’s Closet",
        city: "Charlotte",
        state: "NC",
    },
    { id: "ST208", store: "Detroit Motor Gear", city: "Detroit", state: "MI" },
];